# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "precise32"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  # config.vm.box_url = "http://domain.com/path/to/above.box"

  # Set hostname:
  config.vm.hostname = "finpub-ic-mobile"

  # Share an additional folder to the guest VM:
  config.vm.synced_folder "~/Sites/finpub-ic-mobile", "/vagrant-project"

  # Provision using shell
  config.vm.provision :shell, :path => "conf/bootstrap.sh"

  # Forwarded ports:
  # HTTP:
  config.vm.network :forwarded_port, guest: 80, host: 8080
  # MySQL (see also http://stackoverflow.com/a/12300228/192331)
  # config.vm.network :forwarded_port, guest: 3306, host: 3307

  # Private network, which allows host-only access to the machine using a specific IP:
  config.vm.network :private_network, ip: "192.168.42.2"

  # Public network matched to bridged network.
  #config.vm.network :public_network, bridge: "en1: USB Ethernet"

  # Uncomment to enable GUI for VM debugging
  # config.vm.provider :virtualbox do |vb|
  #   vb.gui = true
  # end

end
